# Generated by Django 4.0.3 on 2022-04-11 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('verbose_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricePredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField()),
                ('branches_total_coins', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PricePredictionParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(editable=False)),
                ('end_at', models.DateTimeField(editable=False)),
                ('eval_time', models.DateTimeField(db_index=True, editable=False)),
                ('m', models.PositiveIntegerField()),
                ('n', models.PositiveIntegerField()),
                ('branches', models.TextField()),
                ('coin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_prediction_params', to='coin.coin')),
            ],
        ),
        migrations.CreateModel(
            name='PricePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.TextField()),
                ('predicted_at', models.DateTimeField(auto_now=True)),
                ('coin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_predictions', to='coin.coin')),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_predictions', to='coin.pricepredictionresult')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_predictions', to='user.customuser')),
            ],
        ),
    ]
